issue-845-fix: true
with-expecter: true
resolve-type-alias: false
dir: "{{ .InterfaceDir }}/mocks"
outpkg: "mocks"
filename: "mock_{{ .InterfaceName | snakecase | lower }}.go"
mockname: "{{ .InterfaceName }}"
packages:
  github.com/Ethernal-Tech/blockchain-event-tracker/store:
    config:
      all: true
  github.com/Ethernal-Tech/blockchain-event-tracker/tracker:
    config:
      all: true
